### ISSUE TITLE
Fix padding issue on small mobile

### ISSUE THREAD

**Issue by aavdiere** [CenEkaGent/ceneka.ugent.be#24]
Eliminate the padding on mobile for multiple pages (`Bestuur` and `About`). See example image.
![22429300_1464176300303295_1887471947_o](https://user-images.githubusercontent.com/13749144/31444500-a8b0f748-ae9c-11e7-8486-e90534847588.jpg)

This should stretch from left to right with about 5 milimeter padding at each side to not have the text stick to the side of the mobile screen.

**Comment by tverum** [comment]
Fixed, still on branch /applications
